/* NOAH — projectdata voor de realisatiepagina's.
   Eén bron voor de detailpagina (realisatie-detail.html?p=slug) en de
   "gerelateerde realisaties". Foto's zijn tijdelijke stockbeelden. */
window.NOAH_PROJECTS = {
  "spouwmuur-brasschaat": {
    cat: "Isolatie", filter: "isolatie", gemeente: "Brasschaat",
    titel: "Spouwmuurisolatie", accent: "vrijstaande woning",
    lead: "Een vrijstaande woning uit de jaren '70 kreeg in één dag volledig geïsoleerde spouwmuren — zonder breekwerk en met direct voelbaar resultaat.",
    probleem: "hoge stookkosten en koude muren in de winter.",
    aanpak: "EPS-parels ingeblazen via kleine boorgaten in de voegen.",
    resultaat: "tot 25% lagere stookkosten en een gelijkmatige binnentemperatuur.",
    facts: { "Type werk": "Spouwmuurisolatie", "Locatie": "Brasschaat", "Type pand": "Vrijstaande woning", "Duur": "1 dag", "Diensten": "Isolatie" },
    before: "assets/img/realisaties/before.jpg", after: "assets/img/realisaties/r5.jpg",
    gallery: ["assets/img/realisaties/r5.jpg", "assets/img/dienst-isolatie.jpg", "assets/img/realisaties/before.jpg", "assets/img/realisaties/r1.jpg"],
    alts: ["Inblazen van isolatieparels bij het raam", "Glaswolisolatie in de wand", "Werf tijdens de voorbereiding", "Interieur na afwerking"],
  },
  "totaalrenovatie-antwerpen": {
    cat: "Renovatie", filter: "renovatie", gemeente: "Antwerpen",
    titel: "Totaalrenovatie", accent: "rijwoning",
    lead: "Een verouderde rijwoning volledig getransformeerd tot een energiezuinige, comfortabele gezinswoning — van ruwbouw tot afwerking.",
    probleem: "vocht, koudebruggen en een gedateerde indeling.",
    aanpak: "na-isolatie, nieuwe indeling en volledige binnenafwerking.",
    resultaat: "een energiezuinige, lichte en moderne gezinswoning.",
    facts: { "Type werk": "Totaalrenovatie", "Locatie": "Antwerpen", "Type pand": "Rijwoning", "Duur": "± 12 weken", "Diensten": "Isolatie · Renovatie" },
    before: "assets/img/realisaties/slider-before.jpg", after: "assets/img/realisaties/slider-after.jpg",
    gallery: ["assets/img/realisaties/slider-before.jpg", "assets/img/realisaties/r1.jpg", "assets/img/realisaties/r6.jpg", "assets/img/realisaties/r7.jpg", "assets/img/realisaties/before.jpg", "assets/img/realisaties/slider-after.jpg"],
    alts: ["Gestripte woning voor de werken", "Kamer tijdens de renovatie", "Schilderwerk in uitvoering", "Pleisterwerk van de wanden", "Plaatsing van het schrijnwerk", "Afgewerkte leefruimte"],
  },
  "crepi-schoten": {
    cat: "Gevelwerken", filter: "gevel", gemeente: "Schoten",
    titel: "Crepi-gevel", accent: "met isolatie",
    lead: "Buitenmuurisolatie afgewerkt met strakke witte crepi: een nieuwe uitstraling én een betere EPC-score in één beweging.",
    probleem: "een verweerde gevel zonder isolatiewaarde.",
    aanpak: "isolatieplaten op de buitengevel, afgewerkt met siliconencrepi.",
    resultaat: "een strakke, onderhoudsarme gevel die de woning zichtbaar opwaardeert.",
    facts: { "Type werk": "Gevelisolatie + crepi", "Locatie": "Schoten", "Type pand": "Halfopen bebouwing", "Duur": "± 2 weken", "Diensten": "Gevelbekleding · Isolatie" },
    before: "assets/img/realisaties/r9.jpg", after: "assets/img/realisaties/r3.jpg",
    gallery: ["assets/img/realisaties/r3.jpg", "assets/img/dienst-gevel.jpg", "assets/img/realisaties/r7.jpg", "assets/img/realisaties/after.jpg"],
    alts: ["Pleisterwerk van de gevelafwerking", "Aanbrengen van de sierpleister", "Gladstrijken van de afwerklaag", "Resultaat met verzorgde buitenruimte"],
  },
  "dak-leien-kapellen": {
    cat: "Dakwerken", filter: "dak", gemeente: "Kapellen",
    titel: "Dakrenovatie", accent: "met natuurleien",
    lead: "Volledige dakrenovatie met natuurleien en geïntegreerde isolatie — waterdicht en mooi voor decennia.",
    probleem: "versleten dakbedekking met beginnende lekkage.",
    aanpak: "nieuw dampopen onderdak, isolatie en natuurleien.",
    resultaat: "een 100% water- en winddicht dak met topisolatie.",
    facts: { "Type werk": "Dakrenovatie", "Locatie": "Kapellen", "Type pand": "Vrijstaande woning", "Duur": "± 3 weken", "Diensten": "Dakwerken · Isolatie" },
    before: "assets/img/realisaties/r8.jpg", after: "assets/img/dienst-dak.jpg",
    gallery: ["assets/img/dienst-dak.jpg", "assets/img/realisaties/r8.jpg", "assets/img/realisaties/r4.jpg", "assets/img/hero-new.jpg"],
    alts: ["Dakwerkers leggen de nieuwe pannen", "Verwijderen van de oude dakbedekking", "Werken op hoogte aan de gevel", "Afgewerkte woning"],
  },
  "sarking-brasschaat": {
    cat: "Isolatie", filter: "isolatie", gemeente: "Brasschaat",
    titel: "Dakisolatie", accent: "sarkingmethode",
    lead: "Isolatie bovenop de dakstructuur (sarking) tijdens een dakrenovatie: koudebruggen volledig uitgesloten.",
    probleem: "warmteverlies via het dak en oververhitting in de zomer.",
    aanpak: "sarking-isolatieplaten over de volledige dakstructuur.",
    resultaat: "merkbaar koeler in de zomer, warmer in de winter, betere EPC.",
    facts: { "Type werk": "Sarking-dakisolatie", "Locatie": "Brasschaat", "Type pand": "Vrijstaande woning", "Duur": "± 1 week", "Diensten": "Isolatie · Dakwerken" },
    before: "assets/img/realisaties/r8.jpg", after: "assets/img/dienst-isolatie.jpg",
    gallery: ["assets/img/dienst-isolatie.jpg", "assets/img/realisaties/r5.jpg", "assets/img/dienst-dak.jpg", "assets/img/realisaties/r1.jpg"],
    alts: ["Plaatsing van de isolatielaag", "Detail van het isolatiewerk", "Dakwerken in uitvoering", "Interieur na de werken"],
  },
  "zolder-wijnegem": {
    cat: "Renovatie", filter: "renovatie", gemeente: "Wijnegem",
    titel: "Zolderinrichting", accent: "met dakramen",
    lead: "Een ongebruikte zolder omgebouwd tot lichte slaapkamer met eigen dakramen, inclusief isolatie en volledige afwerking.",
    probleem: "verloren ruimte onder een ongeïsoleerd dak.",
    aanpak: "dakisolatie, gyproc-afwerking, dakramen en verlichting.",
    resultaat: "een volwaardige extra kamer en meer woningwaarde.",
    facts: { "Type werk": "Zolderinrichting", "Locatie": "Wijnegem", "Type pand": "Rijwoning", "Duur": "± 4 weken", "Diensten": "Renovatie · Isolatie" },
    before: "assets/img/realisaties/r9.jpg", after: "assets/img/realisaties/r7.jpg",
    gallery: ["assets/img/realisaties/r7.jpg", "assets/img/realisaties/r6.jpg", "assets/img/realisaties/r1.jpg", "assets/img/realisaties/slider-after.jpg"],
    alts: ["Afwerking van de wanden", "Schilderwerk van de nieuwe kamer", "Detailafwerking bij het raam", "Afgewerkte lichte ruimte"],
  },
  "steenstrips-ekeren": {
    cat: "Gevelwerken", filter: "gevel", gemeente: "Ekeren",
    titel: "Steenstrips", accent: "op geïsoleerde gevel",
    lead: "Buitenisolatie afgewerkt met echte baksteenstrips: het authentieke karakter bleef, de energiefactuur daalde.",
    probleem: "koude gevels, maar de baksteenlook moest blijven.",
    aanpak: "isolatieplaten met verlijmde steenstrips en onzichtbare voegen.",
    resultaat: "niet te onderscheiden van metselwerk, mét isolatiewaarde.",
    facts: { "Type werk": "Gevelisolatie + steenstrips", "Locatie": "Ekeren", "Type pand": "Halfopen bebouwing", "Duur": "± 2 weken", "Diensten": "Gevelbekleding · Isolatie" },
    before: "assets/img/realisaties/r9.jpg", after: "assets/img/realisaties/r4.jpg",
    gallery: ["assets/img/realisaties/r4.jpg", "assets/img/dienst-gevel.jpg", "assets/img/realisaties/r3.jpg", "assets/img/hero-new.jpg"],
    alts: ["Gevelwerken met hoogtewerker", "Afwerking van de gevel", "Pleister- en voegwerk", "Strakke afgewerkte woning"],
  },
  "dakvernieuwing-merksem": {
    cat: "Dakwerken", filter: "dak", gemeente: "Merksem",
    titel: "Volledige", accent: "dakvernieuwing",
    lead: "Na stormschade werd het volledige dak vernieuwd: nieuwe structuur, isolatie en dakbedekking in drie weken.",
    probleem: "stormschade en een verouderde, lekkende dakstructuur.",
    aanpak: "volledige vernieuwing van structuur, onderdak en bedekking.",
    resultaat: "een veilig, waterdicht dak met decennialange levensduur.",
    facts: { "Type werk": "Dakvernieuwing", "Locatie": "Merksem", "Type pand": "Rijwoning", "Duur": "± 3 weken", "Diensten": "Dakwerken" },
    before: "assets/img/realisaties/r8.jpg", after: "assets/img/dienst-dak.jpg",
    gallery: ["assets/img/realisaties/r8.jpg", "assets/img/dienst-dak.jpg", "assets/img/realisaties/r4.jpg", "assets/img/realisaties/r2.jpg"],
    alts: ["Afbraak van het oude dak", "Plaatsing van de nieuwe pannen", "Werken aan de dakrand", "Afwerking van de buitenruimte"],
  },
  "buitenrenovatie-wommelgem": {
    cat: "Renovatie", filter: "renovatie", gemeente: "Wommelgem",
    titel: "Buitenrenovatie", accent: "met nieuw schrijnwerk",
    lead: "Terras, buitenschrijnwerk en gevelafwerking in één project vernieuwd voor een frisse, onderhoudsarme buitenkant.",
    probleem: "verouderd schrijnwerk en een vermoeide buitenaanblik.",
    aanpak: "nieuw schrijnwerk, herstelde gevels en een vernieuwd terras.",
    resultaat: "een buitenkant die weer jaren meekan, klaar voor elk seizoen.",
    facts: { "Type werk": "Buitenrenovatie", "Locatie": "Wommelgem", "Type pand": "Vrijstaande woning", "Duur": "± 2 weken", "Diensten": "Renovatie" },
    before: "assets/img/realisaties/r9.jpg", after: "assets/img/realisaties/r2.jpg",
    gallery: ["assets/img/realisaties/r2.jpg", "assets/img/realisaties/after.jpg", "assets/img/realisaties/r6.jpg", "assets/img/hero-new.jpg"],
    alts: ["Buitenwerken aan de woning", "Tuin en oprit na de werken", "Binnenafwerking", "Vooraanzicht van de woning"],
  },
};
